
services:
  postgres:
    container_name: 'PSQL226'
    ports:
      - '5433:5432'
    environment:
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=ev'
      - 'POSTGRES_DB=evdb'
    image: 'postgres:13.16'

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_226
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka_226
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092


  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8060:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true

